volumes:
  volume-pgdata:

services:
  revproxy:
    container_name: revproxy
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./revproxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
      - adminer
    networks:
      shorturl:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://localhost/api
    ports:
      - 3000:80
    networks:
      shorturl:

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://shorturl:shorturl@db/shorturl
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      shorturl:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=shorturl
      - POSTGRES_PASSWORD=shorturl
      - POSTGRES_DATABASE=shorturl
    ports:
      - 5432:5432
    volumes:
      - volume-pgdata:/var/lib/postgresql/data
    networks:
      shorturl:

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      shorturl:

networks:
  shorturl: